name: CI/CD Pipeline for Docker

# Trigger this workflow on push to the 'master' branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest # Use GitHub-hosted runners

    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: SSH into EC2 instance (Amazon Linux 2023) and clone the repo and build Docker container there
    - name: SSH into EC2 and deploy Docker container
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Install Git (if not already installed)
          sudo yum install git -y

          # Clone the repository only if it does not already exist
          if [ ! -d "/home/ec2-user/githubactions" ]; then
            git clone https://github.com/farhan-shaukat/githubactions.git
          fi

          # Navigate to the project folder
          cd /home/ec2-user/githubactions

          # Pull the latest changes from GitHub
          git pull origin master

          # Build the Docker image
          docker build -t my-app .

          # Stop and remove any existing container (if exists)
          docker stop my-app || true
          docker rm my-app || true

          # Run the new Docker container
          docker run -d -p 8080:8080 --name my-app my-app:latest
